name: Sadece TR

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir çalışır
  workflow_dispatch:  # Manuel çalıştırma için

permissions:
  contents: write

jobs:
  filter-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Full Channel List
        run: curl -L -o original.m3u "https://sinetech-nettv.hf.space/playlist/channels"

      - name: Extract Turkey Channels
        run: |
          echo '#EXTM3U' > nettv-tr.m3u
          grep -A 1 -i 'group-title="TURKEY"' oynat/original.m3u | grep -v -- "^--$" >> oynat/nettv-tr.m3u

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add oynat/nettv-tr.m3u oynat/original.m3u  # Dosyaları explicit olarak ekliyoruz
          git diff --quiet && git diff --staged --quiet || git commit -m "TR listesi güncellendi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
